[package]
name = "s3-template-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
rust-s3 = "0.35.1"
uuid = { version = "1.16.0", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
